### ISSUE TITLE
"fuzzy.nvim: Cannot find neither fzy nor fzf. Please install either" with fzf installed

### ISSUE THREAD

**Issue by ashuradji** [tzachar/fuzzy.nvim#1]
Hi, I'm getting this message but i have fzf installed

I'm running Kubuntu 22.04.01 LTS

**Comment by tzachar** [comment]
https://github.com/tzachar/fuzzy.nvim#installation

**Comment by ashuradji** [comment]
I had to go to `'nvim-telescope/telescope-fzf-native.nvim'` path & run `make` manually. Thanks!
