### ISSUE TITLE
Pass some extra data associated with each line through the matcher interface 

### ISSUE THREAD

**Issue by IndianBoy42** [tzachar/fuzzy.nvim#2]
For example we may be searching through lines in buffers and windows and want to remember the line number, bufnr, etc

I think a backwards compatible interface is to let the second argument (`lines`) be a list of tables, if it is then we do the scoring/matching on `line[0]` and then, if matched, return the whole table as is. I think we can also return the index even if the element is a string since that is probably the most commonly needed data

If that sounds okay I can submit a PR

**Comment by tzachar** [comment]
I would not change the current interface, but would rather add a new entry point. something like 'filter_many'.

**Comment by IndianBoy42** [comment]
https://github.com/IndianBoy42/fuzzy.nvim

I think it can be done in a backwards compatible way, at least it still works for cmp-fuzzy-buffer. I just check if the 'line' is actually a table and use the first index

**Comment by tzachar** [comment]
but why should it use the same endpoint?
It makes no sense.

**Comment by IndianBoy42** [comment]
What do you mean by endpoint?

**Comment by tzachar** [comment]
define a new function, with the behavior you require

**Comment by IndianBoy42** [comment]
I can but i feel like the behavior is similar enough, it's either matching over a list of strings, or matching over a list of tables (where the first index is the string). It's not stuffing fundamentally different functions/algorithms/behaviors into one function, it's a tiny conditional in the loop

**Comment by tzachar** [comment]
ok, lets see a PR :)
